Server:
  port: 8888

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kotlin-practice
    username: sa
    password:

  graphql:
    servlet:
      enabled: true
      mapping: /graphql
    graphiql:
      enabled: true
      printer:
        enabled: true
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls, .gpls

  jpa:
    database: mysql
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

